[project]
name = "aihub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "common",
    "fastapi>=0.128.0",
    "pydantic-settings>=2.12.0",
    "sentence-transformers>=5.2.2",
    "uvicorn>=0.40.0",
]

[tool.uv.sources]
common = { workspace = true }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
